### ISSUE TITLE
handling more general expressions

### ISSUE THREAD

**Issue by fserra** [leethargo/SCIP.jl#11]
`SCIP` allows for user defined expressions. One could in principle give the evaluations via callbacks (as I guess other solvers do), in case we cannot understand the expression provided to MPB.  
This is probably future future work

**Comment by leethargo** [comment]
I thought we would evaluate neither functions nor derivates and instead just look at the expression graphs. If there's something we don't understand, we should just fail.

**Comment by fserra** [comment]
that is the current functionality... I just though it might be nice to also provide support for weird user defined stuff.

**Comment by mlubin** [comment]
You're pretty screwed if you're solving a nonconvex MINLP without expression graphs

**Comment by fserra** [comment]
sure, but if some crazy user wants to have some :ifelse in their expression
graph, he/she/it is completely screwed.

**Comment by mlubin** [comment]
A lot of expressions involving ``ifelse`` can be reformulated using binary variables. ``ifelse`` is more relevant for continuous NLP.

**Comment by fserra** [comment]
well, this could still be useful for convex minlp, right?

**Comment by mlubin** [comment]
No, use Pajarito :)
